name: kiwims
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - r-base=4.5.2
  - numpy
  - scipy
  - matplotlib
  - pandas
  - plotly
  - wxpython
  - numba
  - llvmlite
  - zlib
  - pip:
      - unidec==7.0.3
