name: Check for R Package Updates

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  check-renv:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2'

      - name: Run renv Check Script
        id: check_step
        shell: pwsh
        run: ./KiwiMS_App/dev/renv-check.ps1

      - name: Send Notification Email
        if: steps.check_step.outputs.updates_found == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Action Required: R Package Updates Found"
          to: marian-freisleben@outlook.com
          from: GitHub Actions
          body: |
            New package updates were detected in your repository.
            Please review the logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}